apiVersion: v1
kind: Secret
metadata:
  name: chat-service-secret
  namespace: blink-chat
  labels:
    app: chat-service
type: Opaque
data:
  # Dummy Secrets- I'll replace it with actual values before deployment
  JWT_SECRET: "eW91ci1qd3Qtc2VjcmV0LWtleQ="
  MONGODB_URI: "bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGI6MjcwMTcvYmxpbmtjaGF0"
  SPRING_MAIL_USERNAME: "eW91ci1lbWFpbEBnbWFpbC5jb20"
  SPRING_MAIL_PASSWORD: "eW91ci1hcHAtcGFzc3dvcmQ"